# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# For any questions about this software or licensing, please email
# opensource@seagate.com or cortx-questions@seagate.com.

InfraMonitor:
    resource_type: SOFTWARE
    resource_id: monitor
    config_cmd: /opt/seagate/halo/install_depot/monitor/config.py
    unconfig_cmd: /opt/seagate/halo/install_depot/monitor/unconfig.py
    validate_cmd: /opt/seagate/halo/install_depot/monitor/validate.py
HBA:
    resource_type: SERVER_HBA
    resource_id: hba
    config_cmd: /opt/seagate/halo/install_depot/hba/config.py
    unconfig_cmd: /opt/seagate/halo/install_depot/hba/unconfig.py
    validate_cmd: /opt/seagate/halo/install_depot/hba/validate.py
Network:
    resource_type: SERVER_NIC
    resource_id: network
    config_cmd: /opt/seagate/halo/install_depot/network/config.py
    unconfig_cmd: /opt/seagate/halo/install_depot/network/unconfig.py
    validate_cmd: /opt/seagate/halo/install_depot/network/validate.py
Kubernetes:
    resource_type: CLUSTER
    resource_id: k8s
    config_cmd: /opt/seagate/halo/install_depot/k8s/config.py
    unconfig_cmd: /opt/seagate/halo/install_depot/k8s/unconfig.py
    validate_cmd: /opt/seagate/halo/install_depot/k8s/validate.py

